# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer0.org1.wheel.io:
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.wheel.io
      - CORE_PEER_ADDRESS=peer0.org1.wheel.io:7051
      #- CORE_PEER_CHAINCODEADDRESS=peer0.org1.wheel.io:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.wheel.io:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.wheel.io/peers/peer0.org1.wheel.io/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.wheel.io/peers/peer0.org1.wheel.io/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - byfn
