version: '2'
networks:
  byfn:
services:
  zookeeper1:
    container_name: zookeeper1
    hostname: zookeeper1
    image: hyperledger/fabric-zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888 quorumListenOnAllIPs=true
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    extra_hosts:
      - "zookeeper1:192.168.1.220"
      - "zookeeper2:192.168.1.219"
      - "zookeeper3:192.168.1.218"
      - "kafka1:192.168.1.220"
      - "kafka2:192.168.1.219"
      - "kafka3:192.168.1.218"
      - "kafka4:192.168.1.216"
    networks:
      - byfn
