version: '2'

networks:
  byfn:
services:
  orderer0.wheel.io:
    container_name: orderer0.wheel.io
    image: hyperledger/fabric-orderer
    environment:
      #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=smartgear_byfn
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

      #- ORDERER_KAFKA_RETRY_LONGINTERVAL=10s
      #- ORDERER_KAFKA_RETRY_LONGTOTAL=100s
      #- ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      #- ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      #- ORDERER_KAFKA_VERBOSE=true
      #- ORDERER_KAFKA_BROKERS=[192.168.1.220:9092,192.168.1.219:9092,192.168.1.218:9092,192.168.1.216:9092]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./crypto-config/ordererOrganizations/wheel.io/orderers/orderer0.wheel.io/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/wheel.io/orderers/orderer0.wheel.io/tls/:/var/hyperledger/orderer/tls
      #- orderer0.wheel.io:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    extra_hosts:
      - "kafka1:192.168.1.220"
      - "kafka2:192.168.1.219"
      - "kafka3:192.168.1.218"
      - "kafka4:192.168.1.216"
    networks:
      - byfn
