version: '2'
networks:
  byfn:
services:
  peer0.org1.wheel.io:
    container_name: peer0.org1.wheel.io
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org1.wheel.io
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=root
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=root
    extra_hosts:
      - "orderer0.wheel.io:192.168.1.216"
      - "orderer1.wheel.io:192.168.1.215"
      - "orderer2.wheel.io:192.168.1.214"
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GODEBUG=netdns=go
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.wheel.io:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wheel.io/peers/peer0.org1.wheel.io/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wheel.io/peers/peer0.org1.wheel.io/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wheel.io/peers/peer0.org1.wheel.io/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wheel.io/users/Admin@org1.wheel.io/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.org1.wheel.io
    extra_hosts:
      - "orderer0.wheel.io:192.168.1.216"
      - "orderer1.wheel.io:192.168.1.215"
      - "orderer2.wheel.io:192.168.1.214"
      #- "peer0.org2.wheel.io:192.168.1.211"
      #- "peer1.baidu.com:192.168.1.212"
    networks:
      - byfn
