version: '2'

networks:
  byfn:
services:

  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
    ports:
      - "9092:9092"
    extra_hosts:
      - "zookeeper1:192.168.1.220"
      - "zookeeper2:192.168.1.219"
      - "zookeeper3:192.168.1.218"
      - "kafka1:192.168.1.220"
      - "kafka2:192.168.1.219"
      - "kafka3:192.168.1.218"
      - "kafka4:192.168.1.216"
    networks:
      - byfn
